[package]
name = "joke_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nostr-bot = "0.2"
compound_duration = "1.2.0"
reqwest = "0.11.11"
tokio = "1.20.1"
